teleop:
  ros__parameters:
    joy_topic: /joy
    twist_topic: /diffbot_base_controller/cmd_vel_unstamped

#    twist_topic: /cmd_vel
    move:
      forward:
        axis: 1
        scale: 0.1
        deadzone: 0.0
      reverse:
        axis: 1
        scale: 0.1
        deadzone: 0.0
      left:
        axis: 0
        scale: 0.1
        deadzone: 0.0
      right:
        axis: 0
        scale: 0.1
        deadzone: 0.0
    turn:
      left:
        axis: 5
        scale: -1.0
        deadzone: 0.0
        offset: 1.0
      right:
        axis: 4
        scale: 1.0
        deadzone: 0.0
        offset: 1.0
