teleop:
  ros__parameters:
    joy_topic: /joy
    twist_topic: /diffbot_base_controller/cmd_vel_unstamped

#    twist_topic: /cmd_vel
    move:
      forward:
        axis: 1
        scale: 3.5
        deadzone: 0.05
      reverse:
        axis: 1
        scale: 3.5
        deadzone: 0.05
      left:
        axis: 0
        scale: 3.5
        deadzone: 0.05
      right:
        axis: 0
        scale: 3.5
        deadzone: 0.05
    turn:
      left:
        axis: 5
        scale: 10.0
        deadzone: 0.05
        offset: 1.0
      right:
        axis: 4
        scale: -10.0
        deadzone: 0.05
        offset: 1.0
