controller_manager:
  ros__parameters:
    update_rate: 30  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diffbot_base_controller:
      type: diff_drive_controller/DiffDriveController

#    imu_broadcaster:
#      type: imu_sensor_broadcaster/IMUSensorBroadcaster


diffbot_base_controller:
  ros__parameters:
    left_wheel_names: ["sprocket_left_joint"]
    right_wheel_names: ["sprocket_right_joint"]

    wheel_separation: 0.15
    #wheels_per_side: 1  # actually 2, but both are controlled by 1 signal
    wheel_radius: 0.0529 # 0.0529 0.02545 0.02325*

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 30.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    #pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.01]
    #twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.01] 


    open_loop: false
    position_feedback: true
    enable_odom_tf: false  # true

    cmd_vel_timeout: 0.3
    #publish_limited_velocity: true
    use_stamped_vel: false
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear.x.has_velocity_limits: false
    linear.x.has_acceleration_limits: false
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 0.5
    linear.x.min_velocity: -0.5
    linear.x.max_acceleration: 0.5
    linear.x.min_acceleration: -0.5
    linear.x.max_jerk: 0.8
    linear.x.min_jerk: -0.8

    angular.z.has_velocity_limits: false
    angular.z.has_acceleration_limits: false
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 1.
    angular.z.min_velocity: -1.
    angular.z.max_acceleration: 1.
    angular.z.min_acceleration: -1.
    angular.z.max_jerk: 0.8
    angular.z.min_jerk: -0.8


#imu_broadcaster:
#  ros__parameters:

#    sensor_name: mpu9250
#    frame_id: imu_link

    # 500 data points
#    static_covariance_orientation: [2.63882e-06, 0.0, 0.0, 7.50018e-06, 0.0, 0.0, 2.89257e-09, 0.0, 0.0]
#    static_covariance_angular_velocity: [2.71413e-07, 0.0, 0.0, 6.79488e-07, 0.0, 0.0, 4.37879e-07, 0.0, 0.0]
#    static_covariance_linear_acceleration: [0.00133755, 0.0, 0.0, 0.000209753, 0.0, 0.0, 0.00143276, 0.0, 0.0]
